name: Zephyr Build, Deploy tagged commits
on: push

jobs:
  build:
    name: Zephyr build action
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Gen version
      run:  ./GIT-VERSION-GEN
    - name: build zepyhr
      uses: ./.github/actions/action-zephyr
    - name: PLTcloud
      uses: bcdevices/pltcloud-action@v1.1.3
      env:
        FILES: ./dist/*
        API_TOKEN: ${{ secrets.API_TOKEN }}
        PROJECT_UUID: ${{ secrets.PROJECT_UUID }}
        DEPLOYMENT_GROUP_UUID: ${{ secrets.DEPLOYMENT_GROUP_UUID }}'
        AUTO_DEPLOY: true
        VERSION: ${{ github.ref }}
    - name: Publish release
      uses: meeDamian/github-release@2.0
      if: contains(github.ref, 'tags')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: dist/*demo*
        gzip: false
